[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.mainnet]
serlaunchalot = "81vBL51YPS5M6yUcgMVe9NcGtKNK48Kip81nXArLewrn"

[programs.devnet]
serlaunchalot = "81vBL51YPS5M6yUcgMVe9NcGtKNK48Kip81nXArLewrn"

[programs.localnet]
serlaunchalot = "81vBL51YPS5M6yUcgMVe9NcGtKNK48Kip81nXArLewrn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=156e83be-b359-4f60-8abb-c6a17fd3ff5f"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "spl-programs/metadata.so"
