[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
skip-lint = true

[programs.mainnet]
serlaunchalot = "6qXDRh3nSj9isLRDpUqXWyK1nR9eHBVLrdLZpjeoNfc"

[programs.devnet]
serlaunchalot = "6qXDRh3nSj9isLRDpUqXWyK1nR9eHBVLrdLZpjeoNfc"

[programs.localnet]
serlaunchalot = "6qXDRh3nSj9isLRDpUqXWyK1nR9eHBVLrdLZpjeoNfc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts"
[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "spl-programs/metadata.so"
