version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: autofun-postgres
    environment:
      POSTGRES_USER: autofun_owner
      POSTGRES_PASSWORD: npg_2PDZgJfEtrh6
      POSTGRES_DB: autofun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: autofun-redis
    command: redis-server --requirepass MDikUKnhRHlURlnORexvVztDTrNCUBze
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: autofun-minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
