services:
  app:
    build: .
    ports:
      - "3069:3069"
    env_file: 
      - .env
    environment:
      - PORT=3069
      - MONGODB_URI=mongodb://mongo:27017/serlaunchalot
      - SOLANA_RPC_URL=https://api.devnet.solana.com

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 
