name = "api"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
[site]
bucket = "./dist"

# Cron triggers
[triggers]
crons = ["*/10 * * * * *"] # Run every 10 seconds

# D1 Database for production
[[d1_databases]]
binding = "DB"
database_name = "autofun"
database_id = "b086a46c-b1c3-4eec-8eca-2abea542e45b"

# R2 bucket for storage
[[r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage"
preview_bucket_name = "autofun-storage-dev"

[vars]
NETWORK = "mainnet"
DECIMALS = "9"
TOKEN_SUPPLY = "1000000000000000000"
VIRTUAL_RESERVES = "1000000000"
CURVE_LIMIT = "1000000000000"

[[durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketDO"]

# Development environment configuration
[env.development]
name = "api-dev"
# Site configuration for development
[env.development.site]
bucket = "./dist"

# Copy vars to development environment
[env.development.vars]
NETWORK = "mainnet"
DECIMALS = "9"
TOKEN_SUPPLY = "1000000000000000000"
VIRTUAL_RESERVES = "1000000000"
CURVE_LIMIT = "1000000000000"

# D1 Database for development
[[env.development.d1_databases]]
binding = "DB"
database_name = "autofun-dev"
database_id = "00ade209-86ac-46a9-bed5-b74aaaac4ad4"

# Add R2 bucket for development
[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage-dev"

# Add Durable Objects configuration for development
[[env.development.durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

# Production environment configuration
[env.production]
name = "api"
# The production database is already defined in the default configuration
