name = "api-dev"
main = "worker/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat_v2" ]

[limits]
cpu_ms = 300_000 # CPU time limit for the worker (300s)

# Add AI Binding - fix to object format
[ai]
binding = "AI"

# Cloudflare Pages configuration
[site]
bucket = "./dist"

# Cron triggers
[triggers]
crons = ["*/1 * * * *"] # Run every 1 minute

# D1 Database for production
[[d1_databases]]
binding = "DB"
database_name = "autofun"
database_id = "b086a46c-b1c3-4eec-8eca-2abea542e45b"

# R2 bucket for storage
[[r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage"

# KV namespace for auth tokens
[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "91bc4666a62044ba816c53a9b2116281"
preview_id = "d2622b59f8dd431eb2468732a5053649"

# Socket.io Durable Objects
[durable_objects]
bindings = [
  { name = "WEBSOCKET_DO", class_name = "WebSocketDO" }
]

# Migration tags
[[migrations]]
tag = "v1"

# Development environment configuration
[env.development]
name = "api-dev"
# Site configuration for development
[env.development.site]
bucket = "./dist"

# Add AI binding for development - fix to object format
[env.development.ai]
binding = "AI"

# Development environment doesn't use cron triggers
# to avoid the ENOENT utime error with registry/api
[env.development.triggers]
crons = ["*/1 * * * *"] # Run every 1 minute

[env.production.vars]
API_URL = "https://api.auto.fun"
NODE_ENV = "production"
NETWORK = "mainnet"
TOKEN_SUPPLY = "1000000000000000"
DEVNET_FRONTEND_URL = "https://develop.autofun.tech"
MAINNET_FRONTEND_URL = "https://autofun.tech"
DECIMALS = "6"
VITE_R2_PUBLIC_URL = "https://storage.autofun.tech"
R2_PUBLIC_URL = "https://storage.autofun.tech"
VITE_SOLANA_NETWORK="mainnet"
CODEX_WEBHOOK_AUTH_TOKEN="mainnet"
MAINNET_SOLANA_RPC_URL="https://mainnet.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
DEVNET_SOLANA_RPC_URL="https://devnet.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
VITE_VIRTUAL_RESERVES="28000000000"
VIRTUAL_RESERVES="28000000000"
CURVE_LIMIT="113000000000"
FIXED_FEE=0
PROGRAM_ID="autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"
VITE_DEV_PROGRAM_ID="autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"
VITE_PROGRAM_ID="autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"

# Copy vars to development environment
[env.development.vars]
NETWORK = "devnet"
DECIMALS = "6"
TOKEN_SUPPLY = "1000000000000000"
VIRTUAL_RESERVES = "2800000000"
CURVE_LIMIT = "11300000000"
VITE_R2_PUBLIC_URL = "https://storage-dev.autofun.tech"
R2_PUBLIC_URL = "https://storage-dev.autofun.tech"
NODE_ENV = "development"
MAINNET_FRONTEND_URL="https://auto.fun"
DEVNET_FRONTEND_URL="https://develop.auto.fun"
AUTH_TOKEN_SALT = "autofun-wallet-auth-salt-dev-env" # Salt for hashing auth tokens in dev
MAINNET_SOLANA_RPC_URL="https://mainnet.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
DEVNET_SOLANA_RPC_URL="https://devnet.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
API_URL = "https://api-dev.auto.fun"
PROGRAM_ID = "autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"
HELIUS_WEBHOOK_AUTH_TOKEN="devnet"
VITE_DEV_PROGRAM_ID="autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"
VITE_PROGRAM_ID="autoUmixaMaYKFjexMpQuBpNYntgbkzCo2b1ZqUaAZ5"

# D1 Database for development
[[env.development.d1_databases]]
binding = "DB"
database_name = "autofun-dev"
database_id = "9d80bef0-48e8-482b-928a-8d9398f6fa04"

# KV namespace for auth tokens in development
[[env.development.kv_namespaces]]
binding = "AUTH_TOKENS"
id = "41026322740f476eb6aa38bbb96cc210"
preview_id = "fe77e6014ebd4cd583d9f2efa53bf3c8"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "e777950a18374cc0a3c1738c715caf68"

# Add R2 bucket for development
[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage-dev"

# Add Socket.io Durable Objects for development
[env.development.durable_objects]
bindings = [
  { name = "WEBSOCKET_DO", class_name = "WebSocketDO" }
]

[env.production.durable_objects]
bindings = [
  { name = "WEBSOCKET_DO", class_name = "WebSocketDO" }
]

# Add migrations for development environment
[[env.development.migrations]]
tag = "v1"

# Production environment configuration
[env.production]
name = "api"

# Add AI binding for production - fix to object format
[env.production.ai]
binding = "AI"

# The production database is already defined in the default configuration

# KV namespace for auth tokens in production (same as default)
[[env.production.kv_namespaces]]
binding = "AUTH_TOKENS"
id = "91bc4666a62044ba816c53a9b2116281"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "0ddd0d2b6b6241e0b206302ea7ed392b"

# D1 Database for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "autofun"
database_id = "b086a46c-b1c3-4eec-8eca-2abea542e45b"

# R2 bucket for storage
[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage"