name = "api"
main = "worker/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat_v2" ]

[limits]
cpu_ms = 300_000 # CPU time limit for the worker (300ms)

# Add AI Binding - fix to object format
[ai]
binding = "AI"

# Cloudflare Pages configuration
[site]
bucket = "./dist"

# Cron triggers
[triggers]
crons = ["*/1 * * * *"] # Run every 1 minute