name = "api"
main = "worker/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat_v2" ]

# Add AI Binding - fix to object format
[ai]
binding = "AI"

# Cloudflare Pages configuration
[site]
bucket = "./dist"

# Cron triggers
[triggers]
crons = ["*/1 * * * *"] # Run every 1 minute

# D1 Database for production
[[d1_databases]]
binding = "DB"
database_name = "autofun"
database_id = "b086a46c-b1c3-4eec-8eca-2abea542e45b"

# R2 bucket for storage
[[r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage"
preview_bucket_name = "autofun-storage-dev"

[vars]
NETWORK = "mainnet"
DECIMALS = "6"
TOKEN_SUPPLY = "1000000000000000"
VIRTUAL_RESERVES = "28000000000"
CURVE_LIMIT = "11300000000"
R2_PUBLIC_URL = "https://pub-30f52db29266428495af0c1aea206af1.r2.dev"
NODE_ENV = "production"
MAINNET_FRONTEND_URL="https://api.autofun.workers.dev"
DEVNET_FRONTEND_URL="https://api-dev.autofun.workers.dev"

# Socket.io Durable Objects
[durable_objects]
bindings = [
  { name = "WebSocketDO", class_name = "WebSocketDO" }
]

# Migration tags
[[migrations]]
tag = "v1"

# Development environment configuration
[env.development]
name = "api-dev"
# Site configuration for development
[env.development.site]
bucket = "./dist"

# Add AI binding for development - fix to object format
[env.development.ai]
binding = "AI"

# Development environment doesn't use cron triggers
# to avoid the ENOENT utime error with registry/api
[env.development.triggers]
crons = ["*/1 * * * *"] # Run every 1 minute

# Copy vars to development environment
[env.development.vars]
NETWORK = "devnet"
DECIMALS = "6"
TOKEN_SUPPLY = "100000000000000"
VIRTUAL_RESERVES = "280000000"
CURVE_LIMIT = "11300000000"
R2_PUBLIC_URL = "https://pub-30f52db29266428495af0c1aea206af1.r2.dev"
NODE_ENV = "development"
MAINNET_FRONTEND_URL="https://api.autofun.workers.dev"
DEVNET_FRONTEND_URL="https://api-dev.autofun.workers.dev"

# D1 Database for development
[[env.development.d1_databases]]
binding = "DB"
database_name = "autofun-dev"
database_id = "00ade209-86ac-46a9-bed5-b74aaaac4ad4"

# Add R2 bucket for development
[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "autofun-storage-dev"

# Add Socket.io Durable Objects for development
[env.development.durable_objects]
bindings = [
  { name = "WebSocketDO", class_name = "WebSocketDO" }
]

# Add migrations for development environment
[[env.development.migrations]]
tag = "v1"

# Production environment configuration
[env.production]
name = "api"

# Add AI binding for production - fix to object format
[env.production.ai]
binding = "AI"

# The production database is already defined in the default configuration
