import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Autogenerate sidebar from the root of the docs folder
    },
  ],
  
  // API documentation sidebar
  api: [
    {
      type: 'autogenerated',
      dirName: '.', // Autogenerate sidebar from the root of the api folder
    },
  ],
};

export default sidebars; 