import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/providers/SessionProvider";
import { getSession } from "@/utils/auth";
import { ToastContainer } from "react-toastify";

const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en" className="h-full">
      <body className={`${dmMono.className} antialiased h-full`}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <ToastContainer autoClose={5000} theme="dark" />
      </body>
    </html>
  );
}
