import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import BondingCurveBar from "@/components/bonding-curve-bar";
import Button from "@/components/button";
import CopyButton from "@/components/copy-button";
import Divider from "@/components/divider";
import SkeletonImage from "@/components/skeleton-image";
import { abbreviateNumber, fromNow, normalizedProgress, shortenAddress, } from "@/utils";
import { Link } from "react-router";
import ShowMoreText from "react-show-more-text";
export default function GridView({ data }) {
    return (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3", children: data?.map((token, _) => (_jsxs(Link, { to: `/token/${token.mint}`, className: "bg-autofun-background-card p-4 rounded-lg border flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-start gap-3 min-w-0", children: [_jsx("div", { className: "size-32 grow shrink-0", children: _jsx(SkeletonImage, { src: token.image, alt: "image" }) }), _jsxs("div", { className: "flex flex-col gap-3 justify-between min-w-0 w-full", children: [_jsxs("div", { className: "flex items-center w-full min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsx("div", { className: "capitalize text-autofun-text-primary text-base font-medium font-satoshi leading-normal truncate min-w-0", children: token.name }), _jsxs("div", { className: "text-autofun-text-secondary text-base font-normal font-dm-mono uppercase leading-normal tracking-widest truncate min-w-0", children: ["$", token.ticker] })] }), _jsx("div", { className: "px-2 py-1 rounded-md border flex ml-auto shrink-0", children: _jsx("div", { className: "text-autofun-text-secondary text-xs font-medium font-dm-mono", children: fromNow(token.createdAt, true) }) })] }), _jsxs("div", { className: "flex flex-col w-full min-w-0", children: [_jsxs("div", { className: "flex items-center justify-between w-full min-w-0", children: [_jsx("div", { className: "text-autofun-text-secondary text-xs font-medium font-satoshi", children: "Market Cap" }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "text-autofun-text-secondary text-xs font-normal font-dm-mono", children: shortenAddress(token.mint) }), _jsx("div", { onClick: (e) => e.stopPropagation(), children: _jsx(CopyButton, { text: token.mint, className: "size-4" }) })] })] }), _jsx("div", { className: "inline-flex justify-start items-center gap-2 min-w-0", children: _jsx("div", { className: "justify-start text-autofun-text-highlight text-xl font-medium font-dm-mono leading-7 truncate", children: abbreviateNumber(token.marketCapUSD) }) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "text-autofun-text-info text-sm font-medium font-dm-mono", children: "Bonding Curve Progress" }), _jsxs("div", { className: "text-autofun-text-highlight text-sm font-normal font-dm-mono", children: [normalizedProgress(token.curveProgress), "%"] })] }), _jsx(BondingCurveBar, { progress: token.curveProgress })] })] }), _jsx(ShowMoreText
                /* Default options */
                , { 
                    /* Default options */
                    lines: 2, more: "Show more", less: "Show less", className: "text-autofun-text-secondary text-xs font-normal font-dm-mono leading-tight min-h-8", anchorClass: "text-autofun-text-primary hover:text-autofun-text-highlight transition-all duration-200", truncatedEndingComponent: " ... ", children: _jsx("span", { className: "text-autofun-text-secondary text-xs font-normal font-dm-mono leading-tight", children: token.description }) }), _jsx("div", { className: "mt-auto", children: _jsx(Divider, {}) }), _jsx(Button, { variant: "primary", size: "large", className: "hover:border-autofun-stroke-highlight", children: "Buy" })] }, token.mint))) }));
}
