import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, } from "@/components/ui/table";
import { formatNumber, fromNow, normalizedProgress, shortenAddress, } from "@/utils";
import { Grid } from "lucide-react";
import { useNavigate } from "react-router";
import BondingCurveBar from "./bonding-curve-bar";
import CopyButton from "./copy-button";
import SkeletonImage from "./skeleton-image";
export function TableView({ data }) {
    const navigate = useNavigate();
    return (_jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { className: "bg-transparent", children: [_jsx(TableHead, { className: "w-[500px]", children: "AI Agents" }), _jsx(TableHead, { className: "text-left", children: "Market Cap" }), _jsx(TableHead, { className: "text-left", children: "24H Volume" }), _jsx(TableHead, { className: "text-left", children: "Holders Count" }), _jsx(TableHead, { className: "text-left", children: "Bonding Curve" }), _jsx(TableHead, { className: "text-right", children: "Creation Time" })] }) }), _jsx(TableBody, { children: data?.map((token) => {
                    return (_jsxs(TableRow, { className: "cursor-pointer", onClick: () => navigate(`/token/${token.mint}`), children: [_jsx(TableCell, { children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "relative size-[50px] rounded-lg bg-[#262626] overflow-hidden", children: token.image ? (_jsx(SkeletonImage, { src: token.image, alt: token.name, className: "w-full h-full object-cover" })) : (_jsx("div", { className: "absolute inset-0 flex items-center justify-center", children: _jsx(Grid, { className: "w-6 h-6 text-[#8C8C8C]" }) })) }), _jsxs("div", { className: "flex flex-col gap-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsx("div", { className: "capitalize text-autofun-text-primary text-base font-medium font-satoshi leading-normal truncate min-w-0", children: token.name }), _jsxs("div", { className: "text-autofun-text-secondary text-base font-normal font-dm-mono uppercase leading-normal tracking-widest truncate min-w-0", children: ["$", token.ticker] })] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "text-autofun-text-secondary text-xs font-normal font-dm-mono", children: shortenAddress(token.mint) }), _jsx("div", { onClick: (e) => e.stopPropagation(), children: _jsx(CopyButton, { text: token.mint, className: "size-4" }) })] })] })] }) }), _jsx(TableCell, { className: "text-left text-[#2FD345]", children: formatNumber(token.marketCapUSD) }), _jsx(TableCell, { className: "text-left", children: formatNumber(token.volume24h) }), _jsx(TableCell, { className: "text-left", children: token.holderCount }), _jsx(TableCell, { className: "text-left", children: _jsxs("div", { className: "flex items-center gap-2 w-full", children: [_jsx(BondingCurveBar, { progress: token.curveProgress }), _jsxs("span", { className: `font-dm-mono text-sm text-white`, children: [normalizedProgress(token.curveProgress), "%"] })] }) }), _jsx(TableCell, { className: "text-right", children: fromNow(token.createdAt) })] }, token.mint));
                }) })] }));
}
