[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
skip-lint = true

[programs.mainnet]
autofun = "aUToHWG2U3E33oDyKm68pwUygDE1sUUGUM1mnLppMVQ"

[programs.devnet]
autofun= "aUToHWG2U3E33oDyKm68pwUygDE1sUUGUM1mnLppMVQ"

[programs.localnet]
autofun = "aUToHWG2U3E33oDyKm68pwUygDE1sUUGUM1mnLppMVQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
wallet = "./uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts"
[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "spl-programs/metadata.so"
