[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
autofun = "aUToHWG2U3E33oDyKm68pwUygDE1sUUGUM1mnLppMVQ"
raydium_vault = "Bi9TwwuBFf15mVVgfVjh4oz65QAGAAo793ioFfX9ugAR"

[programs.mainnet]
autofun = "AnAYdVXqbS87U1DzzuRR4dnooNv7GjfqnSUEVmaKH8xL"
raydium_vault = "Bi9TwwuBFf15mVVgfVjh4oz65QAGAAo793ioFfX9ugAR"

[registry]
url = "https://staked.helius-rpc.com?api-key=3e7503c3-c6b2-44ac-98d4-c309cbcb4074"

[provider]
cluster = "mainnet"
wallet = "./id.json"

[scripts]
check_config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/checkConfig.ts"
init_autofun = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initAutofun.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_change_claimer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changeClaimer.ts"
test_claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/claim.ts"
test_deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.ts"
test_init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initRayVault.ts"
test_nft_balance = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/checkBalance.ts"
test_withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.ts"
update_state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/updateState.ts"
launch_token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchToken.ts"
change_vault_exec = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changeVaultExec.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://staked.helius-rpc.com?api-key=3e7503c3-c6b2-44ac-98d4-c309cbcb4074"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "LockrWmn6K5twhz3y9w1dQERbmgSaRkfnTeTKbpofwE"
