export const ideas = [
  "famous person",
  "movie character",
  "animal",
  "food",
  "vehicle",
  "historical figure",
  "mythical creature",
  "meme",
  "internet personality",
  "brand",
  "product",
  "company",
  "plant",
  "rock",
  "gem",
  "mineral",
  "element",
  "color",
  "crypto",
  "NFT",
  "video game",
  "anime",
  "cartoon",
  "superhero",
  "villain",
  "AI",
  "robot",
  "alien",
  "conspiracy",
  "viral trend",
  "TikTok",
  "emoji",
  "social media",
  "streaming service",
  "podcast",
  "mixtape",
  "urban legend",
  "glitch",
  "hacker",
  "influencer",
  "streamer",
  "speedrun",
  "challenge",
  "YT shorts",
  "Twitch emote",
  "finsta",
  "cat video",
  "shitpost",
  "deepfake",
  "clickbait",
  "vtuber",
  "wojak comic",
  "greentext",
  "DeFi protocol",
  "DAO",
  "cereal mascot",
  "fast food",
  "energy drink",
  "copypasta",
  "reddit thread",
  "Discord server",
  "web3 project",
  "Telegram group",
  "mobile game",
  "battle royale",
  "metaverse",
  "VR experience",
  "indie game",
  "Roblox avatar",
  "Minecraft mod",
  "4chan board",
  "airdrop",
  "stablecoin",
  "yield farm",
  "trading bot",
  "WhatsApp sticker",
  "Snapchat filter",
  "Instagram reel",
  "React component",
  "Figma template",
  "GitHub repo",
  "VS Code extension",
  "ChatGPT prompt",
  "Reddit AMA",
  "YouTube reaction",
  "LinkedIn post",
  "Twitter space",
  "fitness trend",
  "internet challenge",
  "Zoom background",
  "Telegram sticker",
  "sports team",
  "dark web",
  "cyberpunk",
  "pixel art",
  "vaporwave",
  "synthwave",
  "lofi beats",
  "rage comic",
  "esports team",
  "meme stock",
  "crypto winter",
  "bull run",
  "play-to-earn",
  "move-to-earn",
  "dating app",
  "pissing contest",
];

export const adjectives = [
  "stupid",
  "low effort",
  "funny",
  "meme",
  "trending",
  "popular",
  "cool",
  "unique",
  "futuristic",
  "retro",
  "cursed",
  "blessed",
  "savage",
  "cringe",
  "based",
  "chad",
  "sus",
  "poggers",
  "viral",
  "epic",
  "yolo",
  "dank",
  "lit",
  "rekt",
  "fire",
  "goated",
  "smol",
  "vibe",
  "swag",
  "toxic",
  "derp",
  "woke",
  "thicc",
  "fried",
  "shrek",
  "giga",
  "mega",
  "ultra",
  "hyper",
  "deep",
  "glitch",
  "broken",
  "hacked",
  "jacked",
  "flex",
  "sheesh",
  "bussin",
  "clapped",
  "yeet",
  "ratio'd",
  "copypasta",
  "stonks",
  "smh",
  "fomo",
  "salty",
  "sweaty",
  "tilted",
  "pepega",
  "boomer",
  "zoomer",
  "cooked",
  "clout",
  "simp",
  "hopium",
  "copium",
  "maxi",
  "anti",
  "hodl",
  "ngmi",
  "wagmi",
  "shitcoin",
  "moonshot",
  "paperhands",
  "diamond",
  "rugpull",
  "jpegged",
  "ngl",
  "iykyk",
  "deadass",
  "galaxy",
  "himbo",
  "janky",
  "cheugy",
  "mid",
  "rent-free",
  "soy",
  "sigma",
  "unhinged",
  "frfr",
  "ong",
  "unironically",
  "normie",
  "L",
  "W",
  "catfished",
  "NPC",
  "main character",
  "doxxed",
  "pilled",
  "redpilled",
  "blackpilled",
  "doomscrolling",
  "smoothbrain",
  "degens",
  "frens",
  "whale",
  "kms",
  "gaslighting",
  "whataboutism",
  "memeable",
  "clickbaity",
  "parasocial",
  "dicks",
  "butts",
];

export const nouns = [
  "elon",
  "doge",
  "trump",
  "cat",
  "pepe",
  "wojak",
  "chad",
  "karen",
  "boomer",
  "zoomer",
  "doomer",
  "coomer",
  "booba",
  "kek",
  "moon",
  "ape",
  "frog",
  "wojak",
  "chad",
  "soyjak",
  "bruh",
  "musk",
  "bezos",
  "zuck",
  "stonks",
  "tendies",
  "wagmi",
  "ngmi",
  "fomo",
  "hodl",
  "whale",
  "diamond",
  "wojak",
  "pepega",
  "pog",
  "kappa",
  "copium",
  "hopium",
  "wojak",
  "wojack",
  "nft",
  "eth",
  "btc",
  "sol",
  "defi",
  "dao",
  "gwei",
  "wei",
  "block",
  "chain",
  "mint",
  "burn",
  "pump",
  "dump",
  "rug",
  "shill",
  "shiba",
  "floki",
  "akita",
  "cat",
  "frog",
  "grumpy",
  "bored",
  "rekt",
  "monke",
  "wojak",
  "pepe",
  "dank",
  "doggo",
  "catto",
  "fishe",
  "birb",
  "snek",
  "honse",
  "shibe",
  "pupper",
  "chonker",
  "floof",
  "boi",
  "mr",
  "sus",
  "amogus",
  "imposter",
  "vibe",
  "yeet",
  "mood",
  "stan",
  "clout",
  "drip",
  "vibe",
  "fit",
  "normie",
  "anon",
  "wojie",
  "kermit",
  "gritty",
  "cheems",
  "swole",
  "buff",
  "thicc",
  "bonk",
  "horny",
  "simp",
  "incel",
  "chad",
  "stacy",
  "becky",
  "virgin",
  "sigma",
  "alpha",
  "beta",
  "gamma",
  "delta",
  "epsilon",
  "redpill",
  "blackpill",
  "bluepill",
  "pill",
  "anon",
  "sus",
  "sigma",
  "grindset",
  "mindset",
  "king",
  "queen",
  "lord",
  "gigachad",
  "genz",
  "millenial",
  "boomer",
  "doomer",
  "zoomer",
  "coomer",
  "cooler",
  "xqc",
  "ludwig",
  "mizkif",
  "pokimane",
  "ludwig",
  "shroud",
  "ninja",
  "pawg",
  "dream",
  "corpse",
  "sykkuno",
  "hasan",
  "azan",
  "crypto",
  "vbucks",
  "robux",
  "discord",
  "nitro",
  "mod",
  "admin",
  "ban",
  "mute",
  "kick",
  "ratio",
  "cancel",
  "waifu",
  "husbando",
  "senpai",
  "baka",
  "uwu",
  "owo",
  "pogchamp",
];

export const exampleFormats = [
  `
{
  "name": "DogeBonk",
  "symbol": "BONK",
  "description": "The ultimate meme token that combines Doge with bonking powers. Send your friends to horny jail with BONK!",
  "prompt": "A Shiba Inu dog wearing a police hat and holding a bonk bat, digital art style, vibrant colors, meme aesthetic"
}
`,
  `
{
  "name": "PepeCoin",
  "symbol": "PEPE",
  "description": "The rarest Pepe of them all. Each token represents a unique piece of internet history. Feels good man.",
  "prompt": "A rare Pepe frog wearing a crown and holding a golden coin, pixel art style, green and gold color scheme, web3 aesthetic"
}
`,
  `
{
  "name": "AmongBucks",
  "symbol": "SUS",
  "description": "The impostor is hiding in your wallet! Trade these tokens wisely or get ejected from the financial spaceship.",
  "prompt": "An Among Us character holding a bag of money with a suspicious look, digital illustration, vibrant colors, space background"
}
`,
  `
{
  "name": "CatJAM",
  "symbol": "MEOW",
  "description": "Vibing to the blockchain beat. This token pumps to the rhythm of internet culture. Headphones on, volume up!",
  "prompt": "A cool cat wearing headphones and sunglasses, nodding its head to music, neon colors, animated style, party atmosphere"
}
`,
  `
{
  "name": "MoonLambo",
  "symbol": "LAMBO",
  "description": "When moon? When Lambo? Now! This token fuels your rocket to financial freedom. Buckle up for the ride!",
  "prompt": "A Lamborghini parked on the moon with Earth in the background, crypto symbols floating around, hyperrealistic render"
}
`,
  `
{
  "name": "WojackFinance",
  "symbol": "PAIN",
  "description": "Feel the market's emotions through this token. Bull runs feel like Gigachad, bear markets feel like Doomer. Pain is temporary.",
  "prompt": "A split-face Wojak character showing 'bull market' happiness on one side and 'bear market' depression on the other, meme style"
}
`,
  `
{
  "name": "GigaChad",
  "symbol": "CHAD",
  "description": "The strongest token in your portfolio. Never skips a pump day. Flexing those gains while virgin tokens cry.",
  "prompt": "A muscular, black and white Chad figure holding heavy bags labeled 'gains', dramatic lighting, sigma male grindset aesthetic"
}
`,
  `
{
  "name": "MemeCat",
  "symbol": "LOLCAT",
  "description": "I can haz profits? This token brings back the classic internet cats that started it all. Cheezburger included.",
  "prompt": "A classic LOLcat with Impact font meme text above and below, sitting on a pile of cryptocurrency coins, vintage internet aesthetic"
}
`,
  `
{
  "name": "YEETcoin",
  "symbol": "YEET",
  "description": "Throw your investment worries away! This token yeets itself to the moon with no roadmap, no utility, just vibes.",
  "prompt": "A hand throwing a glowing coin into space, motion blur effect, bright colors, meme style with explosion effects"
}
`,
  `
{
  "name": "PixelApe",
  "symbol": "APE",
  "description": "Return to monke with these pixelated primates. Each token gives you membership to the most exclusive jungle club in crypto.",
  "prompt": "A pixelated bored ape wearing sunglasses and a crown, smoking a banana like a cigar, vaporwave colors, 8-bit style"
}
`,
];
