name: Build client

on:
  push:
    paths:
      - "packages/client/**"
  pull_request:
    paths:
      - "packages/client/**"

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.4"

      - name: Install dependencies
        run: bun install
        working-directory: packages/client

      - name: Build client
        run: bun run build
        working-directory: packages/client
