name: Deploy to Cloudflare Workers and Pages

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     name: Run Tests
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Bun
#         uses: oven-sh/setup-bun@v1
#         with:
#           bun-version: latest

#       - name: Install dependencies
#         run: bun install

#       - name: Generate Drizzle migrations
#         run: bun run generate

#       - name: Run worker tests
#         run: bun run test:worker
        
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker and Pages
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://autofun.pages.dev' || 'https://develop.autofun.pages.dev' }}
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        
      - name: Generate Drizzle migrations
        run: bun run generate
      
      - name: Set environment variables
        id: set-env
        run: |
          if [[ $GITHUB_REF == *"main"* ]]; then
            # Worker settings
            echo "WORKER_NAME=api" >> $GITHUB_ENV
            echo "WORKER_ENV=production" >> $GITHUB_ENV
            echo "DB_SUFFIX=" >> $GITHUB_ENV
            # Pages settings
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "DATABASE_NAME=autofun" >> $GITHUB_ENV
            # API URL for production
            echo "VITE_API_URL=https://api.autofun.workers.dev" >> $GITHUB_ENV
            # Solana network for production (should be mainnet)
            echo "VITE_SOLANA_NETWORK=mainnet" >> $GITHUB_ENV
            # Set production-specific values
            echo "VITE_VIRTUAL_RESERVES=2800000000" >> $GITHUB_ENV
            echo "VITE_TOKEN_SUPPLY=1000000000000000" >> $GITHUB_ENV
          else
            # Worker settings
            echo "WORKER_NAME=api-dev" >> $GITHUB_ENV
            echo "WORKER_ENV=development" >> $GITHUB_ENV
            echo "DB_SUFFIX=-dev" >> $GITHUB_ENV
            # Pages settings
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "DATABASE_NAME=autofun-dev" >> $GITHUB_ENV
            echo "DATABASE_NAME_DEV=autofun-dev" >> $GITHUB_ENV
            # API URL for development
            echo "VITE_API_URL=https://api-dev.autofun.workers.dev" >> $GITHUB_ENV
            # Solana network for development
            echo "VITE_SOLANA_NETWORK=devnet" >> $GITHUB_ENV
            # Set devnet-specific values
            echo "VITE_VIRTUAL_RESERVES=280000000" >> $GITHUB_ENV
            echo "VITE_TOKEN_SUPPLY=100000000000000" >> $GITHUB_ENV
          fi
          
          # Common environment variables for both environments
          echo "VITE_DECIMALS=6" >> $GITHUB_ENV
          echo "VITE_BONDING_CURVE_ADDRESS=HzkWnuoMSJRNhyHYrXVPgpyWaPn795bLJNBsfgXF326x" >> $GITHUB_ENV
          echo "VITE_DEV_ADDRESS=6X498a5ujz5zZ5d5LJXqdR28dzDgmLisaAL6Qdq18N9p" >> $GITHUB_ENV
          echo "VITE_RAYDIUM_ADDRESS=GpMZbSM2GgvTKHJirzeGfMFoaZ8UR2X7F4v8vHTvxFbL" >> $GITHUB_ENV
          echo "VITE_DEVNET_RPC_URL=https://devnet.helius-rpc.com/?api-key=7f068738-8b88-4a91-b2a9-99b00f716717" >> $GITHUB_ENV
          echo "VITE_MAINNET_RPC_URL=https://mainnet.helius-rpc.com/?api-key=7f068738-8b88-4a91-b2a9-99b00f716717" >> $GITHUB_ENV
          # Set RPC URL based on network
          if [[ "$VITE_SOLANA_NETWORK" == "mainnet" ]]; then
            echo "VITE_RPC_URL=$VITE_MAINNET_RPC_URL" >> $GITHUB_ENV
          else
            echo "VITE_RPC_URL=$VITE_DEVNET_RPC_URL" >> $GITHUB_ENV
          fi

      # Build frontend before deploying backend
      - name: Build frontend
        run: bun run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          VITE_API_URL: ${{ env.VITE_API_URL }}
          VITE_SOLANA_NETWORK: ${{ env.VITE_SOLANA_NETWORK }}
          VITE_DEVNET_RPC_URL: ${{ env.VITE_DEVNET_RPC_URL }}
          VITE_MAINNET_RPC_URL: ${{ env.VITE_MAINNET_RPC_URL }}
          VITE_RPC_URL: ${{ env.VITE_RPC_URL }}
          VITE_VIRTUAL_RESERVES: ${{ env.VITE_VIRTUAL_RESERVES }}
          VITE_TOKEN_SUPPLY: ${{ env.VITE_TOKEN_SUPPLY }}
          VITE_DECIMALS: ${{ env.VITE_DECIMALS }}
          VITE_BONDING_CURVE_ADDRESS: ${{ env.VITE_BONDING_CURVE_ADDRESS }}
          VITE_DEV_ADDRESS: ${{ env.VITE_DEV_ADDRESS }}
          VITE_RAYDIUM_ADDRESS: ${{ env.VITE_RAYDIUM_ADDRESS }}

      # Apply migrations to D1 database
      - name: Apply D1 migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: d1 execute autofun${{ env.DB_SUFFIX }} --file=./drizzle/migrations.sql --env ${{ env.WORKER_ENV }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      # Publish Durable Object migrations
      - name: Publish Durable Object migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --config wrangler.toml --env ${{ env.WORKER_ENV }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      # Deploy the worker
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --config wrangler.toml --env ${{ env.WORKER_ENV }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          # Database configuration
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          DATABASE_NAME_DEV: ${{ env.DATABASE_NAME_DEV }}
          DATABASE_ID_DEV: ${{ secrets.DATABASE_ID_DEV || '00ade209-86ac-46a9-bed5-b74aaaac4ad4' }}

      # Deploy to Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME || 'autofun' }}
          directory: dist
          branch: ${{ github.ref_name }}
          wranglerVersion: '3'
          # Disable GitHub integration to avoid permission issues
          gitHubToken: ""
          
      # Set environment variables in Cloudflare Pages project
      - name: Set Cloudflare Pages environment variables
        if: success()
        run: |
          echo "Setting environment variables for Cloudflare Pages project: ${{ env.PROJECT_NAME || 'autofun' }}"
          
          # Using wrangler to set environment variables for Pages project
          PROJECT="${{ env.PROJECT_NAME || 'autofun' }}"
          
          # Install Cloudflare Wrangler if not already installed
          npm install -g wrangler
          
          # Set each environment variable
          wrangler pages project env set VITE_SOLANA_NETWORK "$VITE_SOLANA_NETWORK" --project-name "$PROJECT"
          wrangler pages project env set VITE_API_URL "$VITE_API_URL" --project-name "$PROJECT" 
          wrangler pages project env set VITE_DEVNET_RPC_URL "$VITE_DEVNET_RPC_URL" --project-name "$PROJECT"
          wrangler pages project env set VITE_MAINNET_RPC_URL "$VITE_MAINNET_RPC_URL" --project-name "$PROJECT"
          wrangler pages project env set VITE_RPC_URL "$VITE_RPC_URL" --project-name "$PROJECT"
          wrangler pages project env set VITE_VIRTUAL_RESERVES "$VITE_VIRTUAL_RESERVES" --project-name "$PROJECT"
          wrangler pages project env set VITE_TOKEN_SUPPLY "$VITE_TOKEN_SUPPLY" --project-name "$PROJECT"
          wrangler pages project env set VITE_DECIMALS "$VITE_DECIMALS" --project-name "$PROJECT"
          wrangler pages project env set VITE_BONDING_CURVE_ADDRESS "$VITE_BONDING_CURVE_ADDRESS" --project-name "$PROJECT"
          wrangler pages project env set VITE_DEV_ADDRESS "$VITE_DEV_ADDRESS" --project-name "$PROJECT"
          wrangler pages project env set VITE_RAYDIUM_ADDRESS "$VITE_RAYDIUM_ADDRESS" --project-name "$PROJECT"
          
          echo "Environment variables set for $PROJECT"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          
      - name: Notify on Success
        if: success()
        run: |
          echo "Deployment completed successfully!"
          echo "Worker deployed: ${{ env.WORKER_NAME }} (Environment: ${{ env.WORKER_ENV }})"
          
          if [[ "${{ env.WORKER_ENV }}" == "production" ]]; then
            echo "API URL: https://api.autofun.pages.dev"
            echo "Frontend URL: https://autofun.pages.dev"
          else
            echo "API URL: https://api-dev.autofun.pages.dev"
            echo "Frontend URL: https://develop.autofun.pages.dev"
          fi
          
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment failed!"
          echo "Please check the logs for more information and verify your Cloudflare credentials." 