name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set environment variables
        id: set-env
        run: |
          if [[ $GITHUB_REF == *"main"* ]]; then
            echo "PROJECT_NAME=autofun-frontend" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://autofun-frontend.pages.dev" >> $GITHUB_ENV
            echo "NODE_ENV=production" >> $GITHUB_ENV
          else
            echo "PROJECT_NAME=autofun-frontend-dev" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://autofun-frontend-dev.pages.dev" >> $GITHUB_ENV
            echo "NODE_ENV=development" >> $GITHUB_ENV
          fi

      - name: Build frontend
        run: bun run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          wranglerVersion: '3'
          
      - name: Notify on Success
        if: success()
        run: |
          echo "Frontend deployment completed successfully!"
          echo "Deployed to: ${{ env.DEPLOY_URL }}"
          
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Frontend deployment failed!"
          echo "Please check the logs for more information and verify your Cloudflare credentials." 